### ISSUE TITLE
Compatibility with latest cbpi4 version

### ISSUE THREAD

**Issue by avollkopf** [sjhoglund/cbpi4-PressureSensor#1]
The requirement in setup.py does not fir to the latest cbpi4 versions since the package name changed from cbpi to cbpi4.

Therefore, setup.py needs to be changed to work with newer version:

current setup.py:
```
      install_requires=[
          'cbpi>=4.0.0.33',
          'adafruit-circuitpython-ads1x15'
      ],
      
```
should be changed to:
```
      install_requires=[
          'adafruit-circuitpython-ads1x15'
      ],
      
```

**Comment by sjhoglund** [comment]
Sorry for the delay, I haven't been monitoring this repo.
